name: 'push-to-ecr-production'

on:
  release:
    types: [published]
env:
  AWS_REGION: us-east-1
jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: Get component name and version tag
        id: get-tag-components
        run: |
          echo "VERSION_TAG=$(echo $GITHUB_REF | cut -d'/' -f 3 | cut -d'-' -f 2)" >> "$GITHUB_OUTPUT"
          echo "COMPONENT_NAME=$(echo $GITHUB_REF | cut -d'/' -f 3 | cut -d'-' -f 1)" >> "$GITHUB_OUTPUT"
      - name: Display component name and version tag
        env:
          COMPONENT_NAME: ${{ steps.get-tag-components.outputs.COMPONENT_NAME }}
          VERSION_TAG: ${{ steps.get-tag-components.outputs.VERSION_TAG }}
        run: |
          echo "component name: $COMPONENT_NAME"
          echo "version tag: $VERSION_TAG"

